import Head from "next/head";
import { Breadcrumb, Button, Layout } from 'antd';
import { Content, Header } from "antd/es/layout/layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <Header />
      <Breadcrumb>
        <Breadcrumb.Item>Home</Breadcrumb.Item>
      </Breadcrumb>
      <Content>
        <Button type="primary">Button</Button>
      </Content>
      </Layout>
    </>
  );
}
