import Head from "next/head";
import { Breadcrumb, Button, Col, Layout, Row } from 'antd';
import { Content, Header } from "antd/es/layout/layout";
import { getCountRollingMean } from "@/services-calls/gov-data";
import { useQuery } from "@tanstack/react-query";
import { CountChartCard } from "@/components/countChartCard";

export default function Home() {
  const { data } =  useQuery({
    queryKey: ['countRollingMean'],
    queryFn: () => getCountRollingMean().then((res) => res?.data),
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <Header />
      <Content>
        <Breadcrumb>
          <Breadcrumb.Item>Home</Breadcrumb.Item>
        </Breadcrumb>
        <Row>
          <Col sm={24} xl={12}>
            {data && <CountChartCard data={data.results}/>}
          </Col>
          <Col sm={24} xl={12}>
            {data && <CountChartCard data={data.results}/>}
          </Col>
        </Row>
      </Content>
      </Layout>
    </>
  );
}
