import Head from "next/head";
import { Breadcrumb, Button, Layout } from 'antd';
import { Content, Header } from "antd/es/layout/layout";
import { getCountRollingMean } from "@/services-calls/gov-data";
import { useQuery } from "@tanstack/react-query";

export default function Home() {
  const { data } =  useQuery({
    queryKey: ['countRollingMean'],
    queryFn: () => getCountRollingMean(),
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <Header />
      <Content>
        <Breadcrumb>
          <Breadcrumb.Item>Home</Breadcrumb.Item>
        </Breadcrumb>
        {data && <div>{JSON.stringify(data)}</div>}
      </Content>
      </Layout>
    </>
  );
}
